import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@/lib/supabase/server';
import { checkRateLimit } from '@/lib/auth/rateLimit';
import { buildMemoryContext, getUserAIMemory } from '@/lib/ai/memory';
import type { ScheduleBlock } from '@/lib/ai/agentic-scheduler';
import { z } from 'zod';

const refinedBlockSchema = z.object({
  id: z.string(),
  time: z.string(),
  title: z.string(),
  type: z.enum(['focus', 'break', 'event', 'constraint', 'buffer']),
  duration: z.number(),
  description: z.string(),
  specific_action: z.string().optional(),
  success_condition: z.string().optional(),
  why_now: z.string().optional(),
  fallback_if_stuck: z.string().optional(),
  materials_needed: z.array(z.string()).optional(),
  break_reason: z.string().optional(),
  originalTitle: z.string().optional(),
  taskId: z.string().optional(),
  externalUrl: z.string().optional(),
}).passthrough();

const refinedResponseSchema = z.object({
  daily_theme: z.string().nullable().optional(),
  ollie_greeting: z.string().nullable().optional(),
  schedule: z.array(refinedBlockSchema),
});

/**
 * POST /api/ai/schedule-refine
 *
 * Polishes a rule-based schedule while preserving the structured fields the UI
 * needs to explain exactly what the user should do in each block.
 */
export async function POST(request: NextRequest) {
  try {
    const { allowed, error: limitError, message } = await checkRateLimit('schedule-refine');

    if (!allowed) {
      return NextResponse.json(
        { error: limitError, message: message || 'Daily AI limit reached.' },
        { status: limitError === 'Unauthorized' ? 401 : 403 }
      );
    }

    const { schedule, energyLevel } = (await request.json()) as {
      schedule: ScheduleBlock[];
      energyLevel: string;
    };

    if (!schedule || schedule.length === 0) {
      return NextResponse.json({ refined: schedule });
    }

    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    const memoryContext = user
      ? buildMemoryContext(await getUserAIMemory(supabase, user.id))
      : 'No user memory available yet.';

    const openAiApiKey = process.env.OPENAI_API_KEY;
    if (!openAiApiKey) {
      return NextResponse.json({ refined: schedule });
    }

    const prompt = `You are Ollie, the AI assistant for Plan Pilot - a structured daily planning instrument for students.

You are given a draft daily schedule generated by a rule-based engine. Your job is to polish it so it feels motivating, concrete, and useful.

User energy level today: ${energyLevel || 'medium'}

USER MEMORY:
${memoryContext}

DRAFT SCHEDULE:
${JSON.stringify(schedule, null, 2)}

INSTRUCTIONS:
1. Preserve every block and every existing field. Do NOT remove IDs, task IDs, URLs, start/end times, originalTitle, type, time, or duration.
2. Keep task titles recognizable. Do NOT replace task names with vague metaphors.
3. For every focus block, ensure:
   - "specific_action" says exactly what the user should do during that time.
   - "success_condition" says how the user knows the block is done.
   - "why_now" explains why this slot makes sense.
   - "fallback_if_stuck" gives one tiny next step.
4. For every break block, include "break_reason". If the break is not clearly justified, keep the block but describe it as optional recovery.
5. Avoid repeated phrases across descriptions. Avoid generic copy like "stay on track", "make progress", "steady rhythm" unless the sentence has concrete task context.
6. Descriptions must be clear, plain, and no more than 18 words.
7. Add a top-level "daily_theme" string that is useful, not decorative.
8. Add a top-level "ollie_greeting" string - one warm sentence that names the shape of the day.
9. Apply USER MEMORY unless it conflicts with the user's current schedule or fixed calendar events.
10. Return ONLY valid JSON in this exact shape:

{
  "daily_theme": "...",
  "ollie_greeting": "...",
  "schedule": [ ...the polished blocks... ]
}`;

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${openAiApiKey}`,
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        response_format: { type: 'json_object' },
        messages: [{ role: 'system', content: prompt }],
        max_tokens: 2200,
      }),
    });

    if (!response.ok) {
      console.error('Schedule refine API error:', response.status);
      return NextResponse.json({ refined: schedule });
    }

    const data = await response.json();
    const parsed = refinedResponseSchema.safeParse(JSON.parse(data.choices[0].message.content));

    if (!parsed.success) {
      console.error('Schedule refine schema error:', parsed.error.format());
      return NextResponse.json({ refined: schedule });
    }

    return NextResponse.json({
      refined: mergePreservedScheduleFields(schedule, parsed.data.schedule),
      daily_theme: parsed.data.daily_theme || null,
      ollie_greeting: parsed.data.ollie_greeting || null,
    });
  } catch (error) {
    console.error('Schedule refine error:', error);
    return NextResponse.json({ error: 'Refinement failed' }, { status: 500 });
  }
}

function mergePreservedScheduleFields(original: ScheduleBlock[], refined: Array<Record<string, unknown>>) {
  const originalById = new Map(original.map((block) => [String(block.id), block]));

  return refined.map((block) => {
    const originalBlock = originalById.get(String(block.id));
    if (!originalBlock) return block;

    return {
      ...originalBlock,
      ...block,
      id: originalBlock.id,
      time: originalBlock.time,
      type: originalBlock.type,
      duration: originalBlock.duration,
      startTime: originalBlock.startTime,
      endTime: originalBlock.endTime,
      taskId: originalBlock.taskId,
      externalUrl: originalBlock.externalUrl,
      originalTitle: originalBlock.originalTitle,
    };
  });
}
