import type { BrunoActionType, BrunoToolDefinition } from "./types";

export const brunoActionRegistry: Record<BrunoActionType, BrunoToolDefinition> = {
  CREATE_TASK: {
    type: "CREATE_TASK",
    label: "Create task",
    description: "Create a new task in Planevo.",
    riskLevel: "low",
    requiresConfirmation: true,
    executable: true, // Set to true as part of Phase 4C
  },
  UPDATE_TASK: {
    type: "UPDATE_TASK",
    label: "Update task",
    description: "Update an existing task.",
    riskLevel: "medium",
    requiresConfirmation: true,
    executable: true,
  },
  RESCHEDULE_TASK: {
    type: "RESCHEDULE_TASK",
    label: "Reschedule task",
    description: "Move an existing task to another date or time.",
    riskLevel: "medium",
    requiresConfirmation: true,
    executable: true,
  },
  CREATE_TIME_BLOCK: {
    type: "CREATE_TIME_BLOCK",
    label: "Create time block",
    description: "Create a new time block in the plan/calendar.",
    riskLevel: "medium",
    requiresConfirmation: true,
    executable: true,
  },
  UPDATE_CALENDAR_EVENT: {
    type: "UPDATE_CALENDAR_EVENT",
    label: "Update calendar event",
    description: "Move or edit an existing calendar event.",
    riskLevel: "medium",
    requiresConfirmation: true,
    executable: true,
  },
  UPDATE_DAILY_PLAN: {
    type: "UPDATE_DAILY_PLAN",
    label: "Update daily plan",
    description: "Modify the user's daily plan.",
    riskLevel: "high",
    requiresConfirmation: true,
    executable: true,
  },
  EXPLAIN_PLAN: {
    type: "EXPLAIN_PLAN",
    label: "Explain plan",
    description: "Explain a plan or recommendation.",
    riskLevel: "low",
    requiresConfirmation: false,
    executable: true,
  },
  NO_ACTION: {
    type: "NO_ACTION",
    label: "No action",
    description: "No app action is required.",
    riskLevel: "low",
    requiresConfirmation: false,
    executable: true,
  },
  CREATE_NOTE: {
    type: "CREATE_NOTE",
    label: "Create note",
    description: "Create a new note.",
    riskLevel: "low",
    requiresConfirmation: true,
    executable: true,
  },
  UPDATE_NOTE: {
    type: "UPDATE_NOTE",
    label: "Update note",
    description: "Update an existing note.",
    riskLevel: "medium",
    requiresConfirmation: true,
    executable: true,
  },
  APPEND_TO_NOTE: {
    type: "APPEND_TO_NOTE",
    label: "Append to note",
    description: "Append content to an existing note.",
    riskLevel: "low",
    requiresConfirmation: true,
    executable: true,
  },
  ARCHIVE_NOTE: {
    type: "ARCHIVE_NOTE",
    label: "Archive note",
    description: "Archive an existing note.",
    riskLevel: "medium",
    requiresConfirmation: true,
    executable: true,
  },
  DELETE_CALENDAR_EVENT: {
    type: "DELETE_CALENDAR_EVENT",
    label: "Delete calendar event",
    description: "Delete a calendar event.",
    riskLevel: "high",
    requiresConfirmation: true,
    executable: true,
  },
  DELETE_TASK: {
    type: "DELETE_TASK",
    label: "Delete task",
    description: "Delete an existing task.",
    riskLevel: "high",
    requiresConfirmation: true,
    executable: true,
  },
  APPLY_PLAN: {
    type: "APPLY_PLAN",
    label: "Apply plan",
    description: "Apply a multi-step plan of task, calendar, and note changes in one confirmation.",
    riskLevel: "medium",
    requiresConfirmation: true,
    executable: true,
  },
};

export function getActionDefinition(type: BrunoActionType) {
  return brunoActionRegistry[type];
}
