import { NextRequest, NextResponse } from 'next/server';
import { checkRateLimit } from '@/lib/auth/rateLimit';
import type { ScheduleBlock } from '@/lib/ai/scheduler';

/**
 * POST /api/ai/schedule-refine
 *
 * Takes a rule-based ScheduleBlock[] and asks the LLM to "polish" it —
 * rewriting descriptions for motivation, adjusting the rhythm, and
 * adding a cohesive daily theme so the schedule feels human-crafted.
 */
export async function POST(request: NextRequest) {
  try {
    // Rate-limit under the same bucket as the main schedule generation
    const { allowed, error: limitError, message } = await checkRateLimit('schedule-refine');

    if (!allowed) {
      return NextResponse.json(
        { error: limitError, message: message || 'Daily AI limit reached.' },
        { status: limitError === 'Unauthorized' ? 401 : 403 }
      );
    }

    const { schedule, energyLevel } = (await request.json()) as {
      schedule: ScheduleBlock[];
      energyLevel: string;
    };

    if (!schedule || schedule.length === 0) {
      return NextResponse.json({ refined: schedule });
    }

    const openAiApiKey = process.env.OPENAI_API_KEY;
    if (!openAiApiKey) {
      // Graceful fallback — just return the unrefined schedule
      return NextResponse.json({ refined: schedule });
    }

    const prompt = `You are Ollie, the AI navigator for Plan Pilot — a productivity cockpit for students.

You are given a draft daily schedule generated by a rule-based engine. Your job is to **polish it** so it feels motivating and human.

User energy level today: ${energyLevel || 'medium'}

DRAFT SCHEDULE:
${JSON.stringify(schedule, null, 2)}

INSTRUCTIONS:
1. Rewrite each block's "description" to be encouraging, specific, and varied. Avoid repeating the same phrases.
2. Do NOT change the "id", "time", "type", or "duration" fields.
3. You MAY add a motivational prefix to "title" (e.g. "Focus: [Task Name]"), but you MUST keep the core task name recognizable. Do NOT replace it with vague metaphors.
4. Add a top-level "daily_theme" string (e.g. "Operation: Steady Progress" or "Momentum Monday").
5. Add a top-level "ollie_greeting" string — a warm 1-sentence opener for the day.
6. Return ONLY valid JSON in this exact shape:

{
  "daily_theme": "...",
  "ollie_greeting": "...",
  "schedule": [ ...the polished blocks... ]
}`;

    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${openAiApiKey}`,
      },
      body: JSON.stringify({
        model: 'gpt-4o-mini',
        response_format: { type: 'json_object' },
        messages: [{ role: 'system', content: prompt }],
        max_tokens: 1500,
      }),
    });

    if (!response.ok) {
      console.error('Schedule refine API error:', response.status);
      // Fallback to unrefined
      return NextResponse.json({ refined: schedule });
    }

    const data = await response.json();
    const parsed = JSON.parse(data.choices[0].message.content);

    return NextResponse.json({
      refined: parsed.schedule || schedule,
      daily_theme: parsed.daily_theme || null,
      ollie_greeting: parsed.ollie_greeting || null,
    });
  } catch (error) {
    console.error('Schedule refine error:', error);
    return NextResponse.json({ error: 'Refinement failed' }, { status: 500 });
  }
}
